class DeckData :
    deck = {
        'east': 1,
        'west': 2,
        'north': 3,
        'south': 4,
        'space': 5,
        'fa': 6,
        'center': 7,
        'oneCircle': 8,
        'twoCircle': 9,
        'threeCircle': 10,
        'fourCircle': 11,
        'fiveCircle': 12,
        'sixCircle': 13,
        'sevenCircle': 14,
        'eightCircle': 15,
        'nineCircle': 16,
        'oneThousand': 17,
        'twoThousand': 18,
        'threeThousand': 19,
        'fourThousand': 20,
        'fiveThousand': 21,
        'sixThousand': 22,
        'sevenThousand': 23,
        'eightThousand': 24,
        'nineThousand': 25,
        'oneStick': 26,
        'twoStick': 27,
        'threeStick': 28,
        'fourStick': 29,
        'fiveStick': 30,
        'sixStick': 31,
        'sevenStick': 32,
        'eightStick': 33,
        'nineStick': 34,
    }
    deckChinese = {
        '东': 1,
        '西': 2,
        '北': 3,
        '南': 4,
        '白': 5,
        '发': 6,
        '中': 7,
        '一同': 8,
        '三同': 9,
        '三同': 10,
        '四同': 11,
        '五同': 12,
        '六同': 13,
        '七同': 14,
        '八同': 15,
        '九同': 16,
        '一万': 17,
        '二万': 18,
        '三万': 19,
        '四万': 20,
        '五万': 21,
        '六万': 22,
        '七万': 23,
        '八万': 24,
        '九万': 25,
        '一条': 26,
        '二条': 27,
        '三条': 28,
        '四条': 29,
        '五条': 30,
        '六条': 31,
        '七条': 32,
        '八条': 33,
        '九条': 34,
    }
    organizedDeck = [deck['east'], deck['east'], deck['east'], deck['east'],
                            deck['north'], deck['north'], deck['north'], deck['north'],
                            deck['west'], deck['west'], deck['west'], deck['west'],
                            deck['south'], deck['south'], deck['south'], deck['south'],
                            deck['center'], deck['center'], deck['center'], deck['center'],
                            deck['fa'], deck['fa'], deck['fa'], deck['fa'],
                            deck['space'], deck['space'], deck['space'], deck['space'],

                            deck['oneCircle'], deck['oneCircle'], deck['oneCircle'], deck['oneCircle'],
                            deck['twoCircle'], deck['twoCircle'], deck['twoCircle'], deck['twoCircle'],
                            deck['threeCircle'], deck['threeCircle'], deck['threeCircle'], deck['threeCircle'],
                            deck['fourCircle'], deck['fourCircle'], deck['fourCircle'], deck['fourCircle'],
                            deck['fiveCircle'], deck['fiveCircle'], deck['fiveCircle'], deck['fiveCircle'],
                            deck['sixCircle'], deck['sixCircle'], deck['sixCircle'], deck['sixCircle'],
                            deck['sevenCircle'], deck['sevenCircle'], deck['sevenCircle'], deck['sevenCircle'],
                            deck['eightCircle'], deck['eightCircle'], deck['eightCircle'], deck['eightCircle'],
                            deck['nineCircle'], deck['nineCircle'], deck['nineCircle'], deck['nineCircle'],

                            deck['oneStick'], deck['oneStick'], deck['oneStick'], deck['oneStick'],
                            deck['twoStick'], deck['twoStick'], deck['twoStick'], deck['twoStick'],
                            deck['threeStick'], deck['threeStick'], deck['threeStick'], deck['threeStick'],
                            deck['fourStick'], deck['fourStick'], deck['fourStick'], deck['fourStick'],
                            deck['fiveStick'], deck['fiveStick'], deck['fiveStick'], deck['fiveStick'],
                            deck['sixStick'], deck['sixStick'], deck['sixStick'], deck['sixStick'],
                            deck['sevenStick'], deck['sevenStick'], deck['sevenStick'], deck['sevenStick'],
                            deck['eightStick'], deck['eightStick'], deck['eightStick'], deck['eightStick'],
                            deck['nineStick'], deck['nineStick'], deck['nineStick'], deck['nineStick'],

                            deck['oneThousand'], deck['oneThousand'], deck['oneThousand'], deck['oneThousand'],
                            deck['twoThousand'], deck['twoThousand'], deck['twoThousand'], deck['twoThousand'],
                            deck['threeThousand'], deck['threeThousand'], deck['threeThousand'], deck['threeThousand'],
                            deck['fourThousand'], deck['fourThousand'], deck['fourThousand'], deck['fourThousand'],
                            deck['fiveThousand'], deck['fiveThousand'], deck['fiveThousand'], deck['fiveThousand'],
                            deck['sixThousand'], deck['sixThousand'], deck['sixThousand'], deck['sixThousand'],
                            deck['sevenThousand'], deck['sevenThousand'], deck['sevenThousand'], deck['sevenThousand'],
                            deck['eightThousand'], deck['eightThousand'], deck['eightThousand'], deck['eightThousand'],
                            deck['nineThousand'], deck['nineThousand'], deck['nineThousand'], deck['nineThousand'],
                            ]

    def __init__(self):
        print("Initialized Data ... ")
        print("Done")